image: maven:3.6.1-jdk-11 

stages:
    - build
    - test
    - deploy

build : 
    stage : build
    before_script:
        - . conf.sh
    script :
        - cd server && mvn compile

test : 
    stage : test
    before_script:
        - . conf.sh
    script :
        - cd server && mvn test 

deploy : 
    stage : deploy
    before_script:
        - . conf.sh && echo "$CI_SSH_KEY" > ci_private_key.pem && chmod 400 ci_private_key.pem
        - mv ci_private_key.pem server
    script :
        - mvn package 
        - pwd
        - ls -l
<<<<<<< HEAD
        - scp -v -o StrictHostKeyChecking=no -i ci_private_key.pem /builds/p1518166/m1if03_69/server/target/tp4.war gitlabci@192.168.75.115:/opt/tomcat/webapps/v3.war
=======
        - scp -v -o StrictHostKeyChecking=no -i ci_private_key.pem /builds/p1518166/m1if03_69/server/target/server.war gitlabci@192.168.75.115:/opt/tomcat/webapps/v3.war
>>>>>>> ded15464930c2e54fdc607398848e3bb47b067e0
